SELECT CONCAT('google','.com') AS CONCAT_FUNCTION;


SELECT ASCII(ProductID) AS ASCII_CODE
FROM Products;

SELECT ASCII('fotbal') AS COD_ASCII_FOTBAL;

SELECT CHAR(99) AS CODE_TO_CHARACTER;

SELECT LOWER('SQL functions') AS Litere_mici;

SELECT UPPER('SQL functions') AS Majuscule;

SELECT REPLACE('Cluj Napoca',' ','-') AS ORAS;

SELECT GETDATE() AS 'Data si ora'

SELECT MONTH('1991/07/13') AS Luna